<?php
return [
    "translation" => [
        "section" => [
            "main"  => [
                "name"  => "Common",
                "values"  => [
                    "pages" => "Pages",
                    "dashboard" => "Dashboard",
                    "pos"   => "POS",
                    "orders"    => "Orders",
                    "order_status_screen"   => "Order Status Screen",
                    "customers" => "Customers",
                    "inventory" => "Inventory",
                    "products"  => "Products",
                    "category"  => "Category",
                    "table" => "Table",
                    "reports"   => "Reports",
                    "settings"  => "Settings",
                    "logout"    => "Logout",
                    "translations"  => "Translations",
                    "settings"  => "Settings",
                    "account_settings"  => "Account Settings",
                    "app_settings"  => "App Settings",
                    "version"   => "Version",
                    "cooking_status"    => "Cooking Status",
                    "back_to_dashboard" => "Back To Dashboard",
                    "email" => "Email",
                    "password"  => "Password",
                    "enter_email"   => "Enter your email",
                    "enter_password" => "Enter your password",
                    "forgot_password"   => "Forgot password?",
                    "remember_me_next"  => "Remember me next time",
                    "sign_in"   => "Sign in",
                    "sl"    => "Sl",
                    "name"  => "Name",
                    "phone" => "Phone",
                    "phone_number"  => "Phone Number",
                    "address"   => "Address",
                    "actions"   => "Actions",
                    "edit"  => "Edit",
                    "delete"    => "Delete",
                    "close" => "Close",
                    "save"  => 'Save',
                    "view"  => "View",
                    "all_category"  => "All Category",
                    "no_items_found"    => "No Items Were Found",
                    "add"   => "Add",
                    "item"  => "Item",
                    "price" => "price",
                    "qty"   => "QTY",
                    "total" => "Total",
                    "subtotal"  => "Subtotal",
                    "discount"  => "Discount",
                    "enter_discount"  => "Enter Discount",
                    "service_charge"    => "Service Charge",
                    "enter_service_charge"    => "Enter Service Charge",
                    "tax_amount"    => "Tax Amount",
                    "clear_all" => "Clear All",
                    "status"    => "Status",
                    "is_active" => "IsActive",
                    "submit"    => "Submit",
                    "active"    => "Active",
                    "inactive"  => "Inactive",
                    "amount"    => "Amount",
                    "back"  => "Back",
                    "lifetime_orders"   => "Lifetime Orders",
                    "today_order"   => "Today Order",
                    "today_sale"    => "Today Sale",
                    "total_customer"    => "Total Customer",
                    "overview"  => "Overview",
                    "latest_orders" => "Latest Orders",
                    "pending_orders"    => "Pending Orders"
                ],
            ],
            "reports"   => [
                "name"  => "Reports",
                "values"    => [
                    "sales_report"  => "Sales Report",
                    "day_wise_report"   => "Day Wise Sales Report",
                    "item_wise_report"  => "Item Wise Sales Report",
                    "customer_report"   => "Customer Report",
                    "search_customer"   => "Search Customer",
                    "search"    => "Search",
                    "customer_name" => "Customer Name",
                    "total_sales"   => "Total Sales",
                    "total_paid"    => "Total Paid",
                    "balance"   => "Balance",
                    "no_data_found" => "No Data Was Found",
                    "all_customers" => "All Customers",
                    "start_date"    => "Start Date",
                    "end_date"  => "End Date",
                    "date"  => "Date",
                    "no_of_orders"  => "No Of Orders",
                    "sales_total"   => "Sales Total",
                    "payments_received" => "Payments Received",
                    "search_item"   => "Search Item",
                    "all_items" => "All Items",
                    "all_types" => "All Types",
                    "no_orders_found"   => "No Orders were found",
                ],
            ],
            "tables"   => [
                "name"  => "Tables",
                "values"    => [
                    "select_tables"  => "Select Table",
                    "choose_table"  => "Choose Table",
                    "tables"    => "Tables",
                    "new_table" => "New Table",
                    "no_tables_found"   => "No Tables Were Found",
                    "add_new_table" => "Add New Table",
                    "edit_table"    => "Edit Table",
                 
                ],
            ],
            "translations"   => [
                "name"  => "Translations",
                "values"    => [
                    "add_translation"  => "Add Translation",
                    "edit_translation"  => "Edit Translation",
                    "language_name" => "Enter Language Name",
                    "icon"  => "Icon",
                    "is_default"    => "Is Default",
                    "default"   => "Default",
                    "new_translation"   => "New Translation",
                    "translations"  => "Translations",
                    "no_translations_found" => "No Translations Found",

                ],
            ],
            "settings"   => [
                "name"  => "Settings",
                "values"    => [
                    "contact_number"    => "Contact Number",
                    "enter_contact_number"  => "Enter Contact Number",
                    "save_changes"  => "Save Changes",
                    "store_name"    => "Store Name",
                    "enter_store_name"  => "Enter Stpre Name",
                    "application_logo"  => "Application Logo",
                    "fav_icon"  => "Fav Icon",
                    "currency_symbol"   => "Currency Symbol",
                    "enter_currency_symbol" => "Enter Currency Symbol",
                    "tax_percentage"    => "Tax Percentage",
                    "enter_tax_percentage"  => "Enter Tax Percentage",
                ],
            ],
            "customers" => [
                "name"  => "Customers",
                "values"    => [
                    "new_customer"  => "New Customer",
                    "add_new_customer"  => "Add New Customer",
                    "edit_customer" => "Edit Customer",
                    "customer"  => "Customer",
                    "customer_info" => "Customer Info",

                ]
            ],
            "payments" => [
                "name"  => "Payments",
                "values"    => [
                    "payment_type"  => "Payment Type",
                    "cash"  => "Cash",
                    "card"  => "Card",
                    "cheque"  => "Cheque",
                    "bank_transfer"  => "Bank Transfer",
                    "paid_amount"   => "Paid Amount",
                    "enter_payment" => "Enter Payment",
                    "paid"  => "Paid",
                    "unpaid"    => "Unpaid",
                    "enter_paid_amount" => "Enter Paid Amount",
                    "add_payment"   => "Add Payment",
                    

                ]
            ],
            "inventory" => [
                "name"  => "Inventory",
                "values"    => [
                    "search_product"  => "Search Product",
                    "no_items_found"    => "No Items Were Found",
                    "category"  => "Category",
                    "new_category"  => "New Category",
                    "add_new_category"  => "Add New Category",
                    "description"   => "Description",
                    "edit_category" => "Edit Categpry",
                    "no_categories_found"   => "No Categories Were Found",
                    "create_product"    => "Create Product",
                    "edit_product"  => "Edit Product",
                    "product_code"  => "Product Code",
                    "product_name"  => "Product Name",
                    "category"  => "Category",
                    "choose"    => "Choose...",
                    "image" => "Image",
                    "is_veg"    => "IsVeg",
                    "add_addons"    => "Add Addons",
                    "variants" => "Variants",
                    "extras"    => "Extras",
                    "add_variant"   => "Add Variant",
                    "no_variant_addons_found"   => "No Variant Addons Were Found",
                    "no_extra_addons_found" => "No Extra Addons Were Found",
                    "add_extra" => "Add Extra",
                    "add_new"   => "Add New",
                    "new_product" => "New Product",
                    "no_products_found" => "No Products Found",
                    "item_name" => "Item Name",
                    
                ]
            ],
            "orders" => [
                "name"  => "Order",
                "values"    => [
                    "new_order"  => "New Order",
                    "pending"   => "Pending",
                    "cooking"   => "Cooking",
                    "ready" => "Ready",
                    "completed" => "Completed",
                    "order_type"    => "Order Type",
                    "table_no"  => "Table No",
                    "order_no"  => "Order No",
                    "bill_amount"   => "Bill Amount",
                    "mark_as_completed" => "Mark as completed",
                    "order_details" => "Order Details",
                    "order_status"  => "Order Status",
                    "payment_details"   => "Payment Details",
                    "more"  => "More",
                    "actions"   => "Actions",
                    "order_id"  => "Order ID",
                    "order_date"    => "Order Date",
                    "walk_in_customer"  => "Walk In Customer",
                    "table_no"  => "Table No",
                    "dining"    => "Dining",
                    "takeaway"  => 'Takeaway',
                    "delivery"  => "Delivery",
                    "total" => "Total",
                    "paid"  => "Paid",
                    "balance"   => "Balance",
                    "no_orders_found"   => "No Orders were found",
                    "mark_as"   => "Mark As",
                    "bill_total"    => "Bill Total",
                    "place_order"   => "Place Order",
                    "variant_info"  => "If a variant is selected, the variant price is used instead of the product price.",
                    "variant"   => "Variant",
                    "extra" => "Extra",
                    "today_cooking_status"  => "Today Cooking Status",
                    "add_something_to_cart" => "Add Something to the cart!",
                    "no_cooking_items"  => "No Cooking Items",
                    "print_invoice" => "Print Invoice",
                    "print_kot" => "Print KOT",
                    "customer_info" => "Customer Info",
                    "company_info"  => "Company Info",
                    "invoice_info"  => "Invoice Info",
                    "payment_status"   => "Payment Status",
                    //TODO::VIEW ORDER PAGE.
                ]
            ],
            "staffs" => [
                "name"  => "Staffs",
                "values"    => [
                    "new_staff"  => "New Staff",
                    "staffs"  => "Staffs",
                    "staff_name"  => "Staff Name",
                    "enter_staff_name"  => "Enter Staff Name",
                    "permissions"  => "Permissions",
                    "menu_title"  => "Menu Title",
                    "edit_staff"  => "Edit Staff",
                    "create_new_staff"  => "Create New Staff",
                    "no_staffs_found"=>"No staffs were found.."
                ]
            ],
        ],
    ],
];